### keras_tuner is one of the most famous lib.It is very useful now a days.

In [124]:
import pandas as pd
import numpy as np

In [125]:
df = pd.read_csv('diabetes.csv')

In [126]:
df.head(3)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1

In [127]:
df.shape

(768, 9)

In [128]:
df.corr()['Outcome']

Pregnancies                 0.221898
Glucose                     0.466581
BloodPressure               0.065068
SkinThickness               0.074752
Insulin                     0.130548
BMI                         0.292695
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

In [129]:
df = df.drop(columns=['BloodPressure','SkinThickness'])

In [130]:
df.head(3)

   Pregnancies  Glucose  Insulin   BMI  DiabetesPedigreeFunction  Age  Outcome
0            6      148        0  33.6                     0.627   50        1
1            1       85        0  26.6                     0.351   31        0
2            8      183        0  23.3                     0.672   32        1

In [131]:
from sklearn.model_selection import train_test_split

In [132]:
X = df.drop(columns=['Outcome'])
y = df['Outcome']

In [133]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=32)

In [134]:
from sklearn.preprocessing import StandardScaler

In [135]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [136]:
pd.DataFrame(X_train_scaled)

            0         1         2         3         4         5
0   -0.845746 -0.461164 -0.695109 -1.015558 -0.844897 -1.037890
1    0.924554  2.390123 -0.695109  0.992016 -0.055284  0.652018
2   -1.140796 -0.837158  0.157428 -0.445666  0.186984 -0.953395
3    0.629504  1.074144  0.602230  1.807998  0.303631 -0.530918
4   -1.140796  0.384822 -0.695109  0.033562 -0.228759 -1.037890
..        ...       ...       ...       ...       ...       ...
609  1.514654 -1.495147 -0.695109 -0.070055 -0.566738  0.398532
610  3.284955  0.510154  0.324229  0.642310 -0.946589  0.821009
611  0.629504 -1.244485 -0.695109 -0.769468 -0.468036  0.652018
612  0.924554  0.134160  1.297234 -0.860133 -0.922661  0.314037
613 -1.140796  0.666818 -0.695109  0.033562 -0.109121 -0.953395

[614 rows x 6 columns]

In [137]:
import keras
import tensorflow

In [138]:
from keras.layers import Dense
from keras import Sequential

In [139]:
model = Sequential()

In [140]:
model.add(Dense(32,activation="relu",input_dim=6))
model.add(Dense(1,activation="sigmoid"))

D:\Deep_Learning\.venv_tf1\Lib\site-packages\keras\src\layers\core\dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [141]:
model.compile(loss="binary_crossentropy",optimizer="sgd",metrics=['accuracy'])

In [142]:
hist = model.fit(X_train_scaled,y_train,batch_size=32,epochs=10,validation_data=(X_test_scaled,y_test))

Epoch 1/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.3622 - loss: 0.8074 - val_accuracy: 0.3961 - val_loss: 0.8459
Epoch 2/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.4069 - loss: 0.7678 - val_accuracy: 0.4935 - val_loss: 0.7981
Epoch 3/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.4997 - loss: 0.7366 - val_accuracy: 0.5714 - val_loss: 0.7592
Epoch 4/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6308 - loss: 0.6880 - val_accuracy: 0.6169 - val_loss: 0.7267
Epoch 5/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6687 - loss: 0.6714 - val_accuracy: 0.6364 - val_loss: 0.6967
Epoch 6/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6931 - loss: 0.6370 - val_accuracy: 0.6494 - val_loss: 0.6709
Epoch 7/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7158 - loss: 0.6178 - val_accuracy: 0.6558 - val_loss: 0.6496
Epoch 8/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7205 - loss: 0.6036 - val_accuracy: 0.6623 - val_loss: 0.6315
Epoch 9/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7081 - loss: 0.5947 - val_accuracy: 0.6623 - val_loss: 0.6145
Epoch 10/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7023 - loss: 0.5978 - val_accuracy: 0.6558 - val_loss: 0.5992

#

#### The problem is we decide on our own how many layers and how many neuron on each layer.
#### we can automate each value using the library keras tuner

## 1.selecting best optimizer of any data

In [143]:
import keras_tuner as kt

In [153]:
# It is from keras-tuner library.
# hp is a class object
def build_model(hp):
    model1 = Sequential()

    model1.add(Dense(32,activation="relu",input_dim=6))
    model1.add(Dense(1,activation="sigmoid"))

    # there are different types of optimizers use the syntax like hp.Choice
    opt = hp.Choice("optimizer", values=['adam','adadelta','rmsprop','sgd'])
    model1.compile(loss="binary_crossentropy",optimizer=opt,metrics=['accuracy'])

    return model1

In [154]:
tuner = kt.RandomSearch(build_model,objective='val_accuracy',max_trials=7)

In [157]:
tuner.search(X_train_scaled,y_train,epochs=7,validation_data=(X_test_scaled,y_test))

In [158]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'rmsprop'}

In [159]:
# You don't need to train the model again 
# num_model=1 means top 1 model
model_best = tuner.get_best_models(num_models=1)[0]

D:\Deep_Learning\.venv_tf1\Lib\site-packages\keras\src\saving\saving_lib.py:802: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 6 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [160]:
model_best.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape               ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 32)                 │             224 │
├──────────────────────────────────────┼────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 1)                  │              33 │
└──────────────────────────────────────┴────────────────────────────┴─────────────────┘

 Total params: 257 (1.00 KB)

 Trainable params: 257 (1.00 KB)

 Non-trainable params: 0 (0.00 B)

In [161]:
model_best.fit(X_train_scaled,y_train,epochs=100,validation_data=(X_test_scaled,y_test),batch_size=32,initial_epoch=7)

Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.7256 - loss: 0.5266 - val_accuracy: 0.7857 - val_loss: 0.4586
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7662 - loss: 0.4888 - val_accuracy: 0.8052 - val_loss: 0.4510
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7526 - loss: 0.4953 - val_accuracy: 0.7987 - val_loss: 0.4463
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7604 - loss: 0.4855 - val_accuracy: 0.7922 - val_loss: 0.4431
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7629 - loss: 0.4680 - val_accuracy: 0.7987 - val_loss: 0.4413
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7801 - loss: 0.4566 - val_accuracy: 0.7922 - val_loss: 0.4407
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7695 - loss: 0.4617 - val_accuracy: 0.8052 - val_loss: 0.4413
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7759 - loss: 0.4724 - val_accuracy: 0.8052 - val_loss: 0.4409
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7356 - loss: 0.5007 - val_accuracy: 0.8052 - val_loss: 0.4405
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8015 - loss: 0.4392 - val_accuracy: 0.7987 - val_loss: 0.4408
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7872 - loss: 0.4347 - val_accuracy: 0.7922 - val_loss: 0.4407
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7881 - loss: 0.4519 - val_accuracy: 0.7857 - val_loss: 0.4401
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7661 - loss: 0.4829 - val_accuracy: 0.7922 - val_loss: 0.4397
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8070 - loss: 0.4182 - val_accuracy: 0.7857 - val_loss: 0.4395
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7923 - loss: 0.4585 - val_accuracy: 0.7857 - val_loss: 0.4401
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7768 - loss: 0.4423 - val_accuracy: 0.7857 - val_loss: 0.4404
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7637 - loss: 0.4715 - val_accuracy: 0.7857 - val_loss: 0.4406
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7767 - loss: 0.4489 - val_accuracy: 0.7857 - val_loss: 0.4399
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7778 - loss: 0.4552 - val_accuracy: 0.7857 - val_loss: 0.4402
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7735 - loss: 0.4531 - val_accuracy: 0.7857 - val_loss: 0.4419
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7671 - loss: 0.4635 - val_accuracy: 0.7857 - val_loss: 0.4414
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7755 - loss: 0.4546 - val_accuracy: 0.7857 - val_loss: 0.4407
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7933 - loss: 0.4354 - val_accuracy: 0.7922 - val_loss: 0.4404
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7903 - loss: 0.4416 - val_accuracy: 0.7922 - val_loss: 0.4415
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7821 - loss: 0.4593 - val_accuracy: 0.7922 - val_loss: 0.4413
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7658 - loss: 0.4624 - val_accuracy: 0.7857 - val_loss: 0.4405
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7833 - loss: 0.4625 - val_accuracy: 0.7857 - val_loss: 0.4410
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8000 - loss: 0.4444 - val_accuracy: 0.7857 - val_loss: 0.4423
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7836 - loss: 0.4542 - val_accuracy: 0.7857 - val_loss: 0.4445
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7695 - loss: 0.4672 - val_accuracy: 0.7857 - val_loss: 0.4445
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7750 - loss: 0.4591 - val_accuracy: 0.7857 - val_loss: 0.4460
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7886 - loss: 0.4640 - val_accuracy: 0.7857 - val_loss: 0.4458
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7827 - loss: 0.4440 - val_accuracy: 0.7857 - val_loss: 0.4458
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7890 - loss: 0.4458 - val_accuracy: 0.7857 - val_loss: 0.4464
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7825 - loss: 0.4569 - val_accuracy: 0.7727 - val_loss: 0.4476
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7968 - loss: 0.4450 - val_accuracy: 0.7727 - val_loss: 0.4473
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4629 - val_accuracy: 0.7857 - val_loss: 0.4468
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7784 - loss: 0.4555 - val_accuracy: 0.7857 - val_loss: 0.4457
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7919 - loss: 0.4461 - val_accuracy: 0.7857 - val_loss: 0.4466
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7719 - loss: 0.4572 - val_accuracy: 0.7792 - val_loss: 0.4474
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8044 - loss: 0.4367 - val_accuracy: 0.7792 - val_loss: 0.4486
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7846 - loss: 0.4474 - val_accuracy: 0.7857 - val_loss: 0.4489
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7726 - loss: 0.4644 - val_accuracy: 0.7792 - val_loss: 0.4507
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7820 - loss: 0.4673 - val_accuracy: 0.7857 - val_loss: 0.4513
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7689 - loss: 0.4984 - val_accuracy: 0.7792 - val_loss: 0.4508
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7876 - loss: 0.4559 - val_accuracy: 0.7792 - val_loss: 0.4513
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8150 - loss: 0.4275 - val_accuracy: 0.7662 - val_loss: 0.4500
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7681 - loss: 0.4468 - val_accuracy: 0.7727 - val_loss: 0.4518
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7941 - loss: 0.4507 - val_accuracy: 0.7662 - val_loss: 0.4520
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8241 - loss: 0.4144 - val_accuracy: 0.7662 - val_loss: 0.4522
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7784 - loss: 0.4551 - val_accuracy: 0.7727 - val_loss: 0.4525
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7902 - loss: 0.4328 - val_accuracy: 0.7662 - val_loss: 0.4512
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7890 - loss: 0.4703 - val_accuracy: 0.7662 - val_loss: 0.4517
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8215 - loss: 0.4196 - val_accuracy: 0.7662 - val_loss: 0.4515
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7717 - loss: 0.4626 - val_accuracy: 0.7792 - val_loss: 0.4512
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8024 - loss: 0.4256 - val_accuracy: 0.7792 - val_loss: 0.4514
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7867 - loss: 0.4634 - val_accuracy: 0.7792 - val_loss: 0.4514
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8133 - loss: 0.4323 - val_accuracy: 0.7792 - val_loss: 0.4500
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4413 - val_accuracy: 0.7792 - val_loss: 0.4501
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7988 - loss: 0.4441 - val_accuracy: 0.7727 - val_loss: 0.4508
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7904 - loss: 0.4564 - val_accuracy: 0.7662 - val_loss: 0.4517
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7996 - loss: 0.4343 - val_accuracy: 0.7662 - val_loss: 0.4533
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8014 - loss: 0.4283 - val_accuracy: 0.7662 - val_loss: 0.4538
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7978 - loss: 0.4491 - val_accuracy: 0.7662 - val_loss: 0.4530
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7799 - loss: 0.4551 - val_accuracy: 0.7727 - val_loss: 0.4523
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7998 - loss: 0.4506 - val_accuracy: 0.7727 - val_loss: 0.4513
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8175 - loss: 0.4216 - val_accuracy: 0.7727 - val_loss: 0.4525
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7938 - loss: 0.4330 - val_accuracy: 0.7792 - val_loss: 0.4539
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8060 - loss: 0.4436 - val_accuracy: 0.7792 - val_loss: 0.4540
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8105 - loss: 0.4333 - val_accuracy: 0.7857 - val_loss: 0.4537
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7902 - loss: 0.4367 - val_accuracy: 0.7857 - val_loss: 0.4540
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8089 - loss: 0.4209 - val_accuracy: 0.7857 - val_loss: 0.4535
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8025 - loss: 0.4228 - val_accuracy: 0.7857 - val_loss: 0.4532
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7939 - loss: 0.4370 - val_accuracy: 0.7857 - val_loss: 0.4534
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7967 - loss: 0.4638 - val_accuracy: 0.7792 - val_loss: 0.4526
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7978 - loss: 0.4300 - val_accuracy: 0.7792 - val_loss: 0.4526
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7772 - loss: 0.4640 - val_accuracy: 0.7792 - val_loss: 0.4534
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7761 - loss: 0.4530 - val_accuracy: 0.7857 - val_loss: 0.4552
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4334 - val_accuracy: 0.7792 - val_loss: 0.4561
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7874 - loss: 0.4396 - val_accuracy: 0.7792 - val_loss: 0.4556
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8160 - loss: 0.4205 - val_accuracy: 0.7727 - val_loss: 0.4557
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4751 - val_accuracy: 0.7792 - val_loss: 0.4566
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8011 - loss: 0.4299 - val_accuracy: 0.7792 - val_loss: 0.4551
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8083 - loss: 0.4304 - val_accuracy: 0.7792 - val_loss: 0.4551
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8117 - loss: 0.4338 - val_accuracy: 0.7857 - val_loss: 0.4546
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7966 - loss: 0.4481 - val_accuracy: 0.7857 - val_loss: 0.4533
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7959 - loss: 0.4491 - val_accuracy: 0.7857 - val_loss: 0.4550
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8144 - loss: 0.4344 - val_accuracy: 0.7857 - val_loss: 0.4549
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8118 - loss: 0.4160 - val_accuracy: 0.7792 - val_loss: 0.4557
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7964 - loss: 0.4238 - val_accuracy: 0.7857 - val_loss: 0.4547
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7817 - loss: 0.4624 - val_accuracy: 0.7857 - val_loss: 0.4556
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7870 - loss: 0.4406 - val_accuracy: 0.7792 - val_loss: 0.4573
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7847 - loss: 0.4555 - val_accuracy: 0.7792 - val_loss: 0.4577

In [165]:
import shutil
shutil.rmtree('untitled_project')  # or the directory you're using

# Tuning on how many neurons on the layer

In [168]:
def build_model(hp):
    model1 = Sequential()
    # from 8 to 128 neurons like limit
    neurons = hp.Int('units',min_value = 8,max_value = 128,step=8)
    model1.add(Dense(units=neurons,activation="relu",input_dim=6))
    model1.add(Dense(1,activation="sigmoid"))

    model1.compile(loss="binary_crossentropy",optimizer="rmsprop",metrics=['accuracy'])

    return model1

In [169]:
tuner = kt.RandomSearch(build_model,objective='val_accuracy',max_trials=7)

D:\Deep_Learning\.venv_tf1\Lib\site-packages\keras\src\layers\core\dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [170]:
tuner.search(X_train_scaled,y_train,epochs=10,validation_data=(X_test_scaled,y_test))

Trial 7 Complete [00h 00m 03s]
val_accuracy: 0.7922077775001526

Best val_accuracy So Far: 0.8116883039474487
Total elapsed time: 00h 00m 23s

In [174]:
tuner.get_best_hyperparameters()[0].values

{'units': 64}

In [175]:
model_best_neurons = tuner.get_best_models(num_models=1)[0]

D:\Deep_Learning\.venv_tf1\Lib\site-packages\keras\src\layers\core\dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
D:\Deep_Learning\.venv_tf1\Lib\site-packages\keras\src\saving\saving_lib.py:802: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 6 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

## how to select No of layers

In [178]:
import shutil
shutil.rmtree('untitled_project')

In [179]:
def build_model(hp):

    model = Sequential()
    model.add(Dense(64,activation="relu",input_dim=6))
    for i in range(hp.Int('num_layers',min_value=1,max_value=10)):

        model.add(Dense(64,activation="relu"))

    model.add(Dense(1,activation='sigmoid'))

    model.compile(loss="binary_crossentropy",optimizer='rmsprop',metrics=['accuracy'])

    return model

In [180]:
tuner = kt.RandomSearch(build_model,objective='val_accuracy',max_trials=3)

In [181]:
tuner.search(X_train_scaled,y_train,epochs=5,validation_data=(X_test_scaled,y_test))

Trial 3 Complete [00h 00m 04s]
val_accuracy: 0.8116883039474487

Best val_accuracy So Far: 0.8116883039474487
Total elapsed time: 00h 00m 11s

In [184]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 10}

In [185]:
model_best_layers = tuner.get_best_models(1)[0]

D:\Deep_Learning\.venv_tf1\Lib\site-packages\keras\src\layers\core\dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
D:\Deep_Learning\.venv_tf1\Lib\site-packages\keras\src\saving\saving_lib.py:802: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 26 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [187]:
model_best_layers.fit(X_train,y_train,epochs=10,initial_epoch=6,validation_data=(X_test_scaled,y_test))

Epoch 7/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - accuracy: 0.5053 - loss: 11.6089 - val_accuracy: 0.6429 - val_loss: 0.5870
Epoch 8/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6544 - loss: 0.6575 - val_accuracy: 0.6429 - val_loss: 0.5915
Epoch 9/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6234 - loss: 0.6832 - val_accuracy: 0.6429 - val_loss: 0.6036
Epoch 10/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6652 - loss: 0.6701 - val_accuracy: 0.6429 - val_loss: 0.6112

In [188]:
# due to overfitting accuracy decrease
## all at once at next notebook